echo "Chat GPT Simulator"

TEST_NAME=chatgpt_simulator
GRAPH_FILE="${ACT_GRAPH_FILES_DIR}${PATH_SEPARATOR}${TEST_NAME}.act"
CONFIG_FILE=${GRAPH_FILE/.act/.actconfig}
cp $GRAPH_FILE $TEST_NAME.act
cp $CONFIG_FILE $TEST_NAME.actconfig
export ACT_GRAPH_FILE=$TEST_NAME.act
export ACT_CONFIG_FILE=$CONFIG_FILE
export ACT_INPUT_SECRET_TESTE2E_OPENAI_SECRET_KEY=$TESTE2E_OPENAI_SECRET_KEY

export PYTHONIOENCODING=utf-8
#! test actrun
