echo "Test Length"

TEST_NAME=length
GRAPH_FILE="${ACT_GRAPH_FILES_DIR}${PATH_SEPARATOR}${TEST_NAME}.act"
TEST_FILE="${ACT_GRAPH_FILES_DIR}${PATH_SEPARATOR}${TEST_NAME}.txt"
cp $GRAPH_FILE $TEST_NAME.act
cp $TEST_FILE $TEST_NAME.txt
export ACT_GRAPH_FILE=$TEST_NAME.act

#! test actrun

