echo "Test Secret Node"

TEST_NAME=secret
GRAPH_FILE="${ACT_GRAPH_FILES_DIR}${PATH_SEPARATOR}${TEST_NAME}.act"
CONFIG_FILE="${ACT_GRAPH_FILES_DIR}${PATH_SEPARATOR}${TEST_NAME}.actconfig"
cp $GRAPH_FILE $TEST_NAME.act
cp $CONFIG_FILE $TEST_NAME.actconfig
export ACT_GRAPH_FILE=$TEST_NAME.act

export ACT_INPUT_SECRET_API_KEY_123=THIS_IS_A_SECRET_FROM_BASH
export ACT_INPUT_SECRET_API_KEY_ALIAS=THIS_IS_A_SECRET_2_FROM_BASH
#! test actrun
unset ACT_INPUT_SECRET_API_KEY_123
unset ACT_INPUT_SECRET_API_KEY_ALIAS

export ACT_INPUT_SECRETS='{"API_KEY_ALIAS": "THIS_IS_ANOTHER_SECRET_2_FROM_BASH", "API_KEY_123": "THIS_IS_ANOTHER_SECRET_FROM_BASH"}'
#! test actrun
unset ACT_INPUT_SECRETS

# this is being passed to the runtime (look at the order)
#! test actrun --config_file=./secret.actconfig
