// Code generated by actrun. DO NOT EDIT.

package node_interfaces

import "github.com/actionforge/actrun-cli/core" // Adds an item to the end of an array.

// ==> (o) Inputs

const Core_array_add_v1_Input_array core.InputId = "array"
const Core_array_add_v1_Input_exec core.InputId = "exec"
const Core_array_add_v1_Input_item core.InputId = "item"

// Outputs (o) ==> 

// The array with the added item
const Core_array_add_v1_Output_array core.OutputId = "array"
const Core_array_add_v1_Output_exec core.OutputId = "exec"
// The index of the added item
const Core_array_add_v1_Output_index core.OutputId = "index"
