// Code generated by actrun. DO NOT EDIT.

package node_interfaces

import "github.com/actionforge/actrun-cli/core" // Appends one array to another.

// ==> (o) Inputs

const Core_array_append_v1_Input_array1 core.InputId = "array1"
const Core_array_append_v1_Input_array2 core.InputId = "array2"
const Core_array_append_v1_Input_exec core.InputId = "exec"

// Outputs (o) ==> 

// The array with the appended items
const Core_array_append_v1_Output_array core.OutputId = "array"
const Core_array_append_v1_Output_exec core.OutputId = "exec"
