// Code generated by actrun. DO NOT EDIT.

package node_interfaces

import "github.com/actionforge/actrun-cli/core" // Multiplies two or more numbers.

// ==> (o) Inputs

// A set of numbers to multiply together.
const Core_math_multiply_v1_Input_inputs core.InputId = "inputs"

// Outputs (o) ==> 

// The result of the multiplication.
const Core_math_multiply_v1_Output_result core.OutputId = "result"
