// Code generated by actrun. DO NOT EDIT.

package node_interfaces

import "github.com/actionforge/actrun-cli/core" // Fetches and merges changes from the remote repository into the current branch.

// ==> (o) Inputs

// Optional credentials for accessing private repositories. If not provided, the node will use the default Git configuration.
const Core_git_pull_v1_Input_auth core.InputId = "auth"
const Core_git_pull_v1_Input_exec core.InputId = "exec"
// The Git repository object from a clone or open node.
const Core_git_pull_v1_Input_repo core.InputId = "repo"

// Outputs (o) ==> 

// Executes if there is an error during the pull.
const Core_git_pull_v1_Output_exec_err core.OutputId = "exec-err"
// Executes if the pull operation is successful.
const Core_git_pull_v1_Output_exec_success core.OutputId = "exec-success"
