// Code generated by actrun. DO NOT EDIT.

package node_interfaces

import "github.com/actionforge/actrun-cli/core" // Creates a credential object containing an Access Key and its corresponding secret/password.

// ==> (o) Inputs

// The access key or ID.
const Core_credentials_accesskey_v1_Input_access_key core.InputId = "access_key"
// The corresponding password or secret for the access key.
const Core_credentials_accesskey_v1_Input_access_password core.InputId = "access_password"

// Outputs (o) ==> 

// A credential object containing the access key and secret.
const Core_credentials_accesskey_v1_Output_credential core.OutputId = "credential"
