// Code generated by actrun. DO NOT EDIT.

package node_interfaces

import "github.com/actionforge/actrun-cli/core" // Creates a credential object containing a username and password.

// ==> (o) Inputs

// The password for authentication.
const Core_credentials_userpass_v1_Input_password core.InputId = "password"
// The username for authentication.
const Core_credentials_userpass_v1_Input_username core.InputId = "username"

// Outputs (o) ==> 

// A credential object containing the username and password.
const Core_credentials_userpass_v1_Output_credential core.OutputId = "credential"
