// Code generated by actrun. DO NOT EDIT.

package node_interfaces

import "github.com/actionforge/actrun-cli/core" // This node takes an array of strings and joins them together to form a single string.

// ==> (o) Inputs

const Core_string_join_array_v1_Input_delimiter core.InputId = "delimiter"
// The segments of the path to join.
const Core_string_join_array_v1_Input_segments core.InputId = "segments"

// Outputs (o) ==> 

// The joined string.
const Core_string_join_array_v1_Output_result core.OutputId = "result"
