// Code generated by actrun. DO NOT EDIT.

package node_interfaces

import "github.com/actionforge/actrun-cli/core" // Create a directory on the file system.

// ==> (o) Inputs

// If true, creates all parent directories as needed (like mkdir -p). If false, only creates the final directory and fails if parent directories don't exist.
const Core_dir_create_v1_Input_create_parents core.InputId = "create_parents"
const Core_dir_create_v1_Input_exec core.InputId = "exec"
// The path of the directory to create.
const Core_dir_create_v1_Input_path core.InputId = "path"

// Outputs (o) ==> 

// Executes if the directory creation fails.
const Core_dir_create_v1_Output_exec_err core.OutputId = "exec-err"
// Executes if the directory creation is successful.
const Core_dir_create_v1_Output_exec_success core.OutputId = "exec-success"
