// Code generated by actrun. DO NOT EDIT.

package node_interfaces

import "github.com/actionforge/actrun-cli/core" // The entry point for an action graph.

// Outputs (o) ==> 

// A list of command-line arguments passed to the graph.
const Core_start_v1_Output_args core.OutputId = "args"
// A list of environment variables available to the process, in `KEY=VALUE` format. For more information check out [Configuration](./../../../reference/configuration.md).
const Core_start_v1_Output_env core.OutputId = "env"
// Triggers the execution of the next node.
const Core_start_v1_Output_exec core.OutputId = "exec"
// The standard input (stdin) data stream.
const Core_start_v1_Output_stdin core.OutputId = "stdin"
