// Code generated by actrun. DO NOT EDIT.

package node_interfaces

import "github.com/actionforge/actrun-cli/core" // Decode a string from various formats like Base64, Hex, UTF-16, UTF-32, or unescape HTML, URL, JSON, and XML sequences.

// ==> (o) Inputs

// The encoded string to decode.
const Core_string_decode_v1_Input_input core.InputId = "input"
// The decoding operation to apply.
const Core_string_decode_v1_Input_op core.InputId = "op"

// Outputs (o) ==> 

// The resulting decoded string.
const Core_string_decode_v1_Output_result core.OutputId = "result"
