// Code generated by actrun. DO NOT EDIT.

package node_interfaces

import "github.com/actionforge/actrun-cli/core" // Test node for integration tests

// ==> (o) Inputs

const Core_test_v1_Input_input_any_foo123 core.InputId = "input_any-foo123"
const Core_test_v1_Input_input_array_bool_foo123 core.InputId = "input_array_bool-foo123"
const Core_test_v1_Input_input_array_number_foo123 core.InputId = "input_array_number-foo123"
const Core_test_v1_Input_input_array_string_foo123 core.InputId = "input_array_string-foo123"
const Core_test_v1_Input_input_bool_foo123 core.InputId = "input_bool-foo123"
const Core_test_v1_Input_input_iterable_foo123 core.InputId = "input_iterable-foo123"
const Core_test_v1_Input_input_map_string_int32_foo123 core.InputId = "input_map_string_int32-foo123"
const Core_test_v1_Input_input_number_foo123 core.InputId = "input_number-foo123"
const Core_test_v1_Input_input_secret_foo123 core.InputId = "input_secret-foo123"
const Core_test_v1_Input_input_slice_string_foo123 core.InputId = "input_slice_string-foo123"
const Core_test_v1_Input_input_storage_provider_foo123 core.InputId = "input_storage_provider-foo123"
const Core_test_v1_Input_input_stream_foo123 core.InputId = "input_stream-foo123"
const Core_test_v1_Input_input_string_foo123 core.InputId = "input_string-foo123"

// Outputs (o) ==> 

const Core_test_v1_Output_output_any_foo123 core.OutputId = "output_any-foo123"
const Core_test_v1_Output_output_array_bool_foo123 core.OutputId = "output_array_bool-foo123"
const Core_test_v1_Output_output_array_number_foo123 core.OutputId = "output_array_number-foo123"
const Core_test_v1_Output_output_array_string_foo123 core.OutputId = "output_array_string-foo123"
const Core_test_v1_Output_output_bool_foo123 core.OutputId = "output_bool-foo123"
const Core_test_v1_Output_output_map_string_int32_foo123 core.OutputId = "output_map_string_int32-foo123"
const Core_test_v1_Output_output_number_foo123 core.OutputId = "output_number-foo123"
const Core_test_v1_Output_output_slice_string_foo123 core.OutputId = "output_slice_string-foo123"
const Core_test_v1_Output_output_storage_provider_foo123 core.OutputId = "output_storage_provider-foo123"
const Core_test_v1_Output_output_stream_foo123 core.OutputId = "output_stream-foo123"
const Core_test_v1_Output_output_string_foo123 core.OutputId = "output_string-foo123"
