// Code generated by actrun. DO NOT EDIT.

package node_interfaces

import "github.com/actionforge/actrun-cli/core" // List of environment variables.

// ==> (o) Inputs

// The list of environment variables that you want to add. These fields support the [Expression Syntax](./../../../reference/expressions.md).
const Core_env_array_v1_Input_env core.InputId = "env"

// Outputs (o) ==> 

// The list of environment variables that includes the provided list of environment variables.
const Core_env_array_v1_Output_env core.OutputId = "env"
