// Code generated by actrun. DO NOT EDIT.

package node_interfaces

import "github.com/actionforge/actrun-cli/core" // Run Python code in an existing Python environment.

// ==> (o) Inputs

// Arguments to pass to the script.
const Core_run_python_embedded_v1_Input_args core.InputId = "args"
const Core_run_python_embedded_v1_Input_exec core.InputId = "exec"
// The script to run.
const Core_run_python_embedded_v1_Input_script core.InputId = "script"
// Stream to pass to the scripts stdin.
const Core_run_python_embedded_v1_Input_stdin core.InputId = "stdin"

// Outputs (o) ==> 

const Core_run_python_embedded_v1_Output_exec_err core.OutputId = "exec-err"
const Core_run_python_embedded_v1_Output_exec_success core.OutputId = "exec-success"
// Value returned by the `main` function within the script. Supported return values and types are `None`, `bool`, `float`, and `str`. Any other data type will throw a runtime error.
const Core_run_python_embedded_v1_Output_return core.OutputId = "return"
