// Code generated by actrun. DO NOT EDIT.

package node_interfaces

import "github.com/actionforge/actrun-cli/core" // Node to download an object from a remote storage.

// ==> (o) Inputs

const Core_storage_download_v1_Input_exec core.InputId = "exec"
const Core_storage_download_v1_Input_name core.InputId = "name"
const Core_storage_download_v1_Input_provider core.InputId = "provider"

// Outputs (o) ==> 

const Core_storage_download_v1_Output_data core.OutputId = "data"
const Core_storage_download_v1_Output_exec core.OutputId = "exec"
const Core_storage_download_v1_Output_provider core.OutputId = "provider"
