// Code generated by actrun. DO NOT EDIT.

package node_interfaces

import "github.com/actionforge/actrun-cli/core" // Compresses files and directories into a single archive.

// ==> (o) Inputs

// A common directory path to remove from the start of file paths, creating a relative structure inside the archive. Relative paths are resolved from the current working directory.
const Core_file_compress_v1_Input_base_path core.InputId = "base_path"
// Starts the compression process.
const Core_file_compress_v1_Input_exec core.InputId = "exec"
const Core_file_compress_v1_Input_format core.InputId = "format"
// Compression level from 0 (none) to 9 (best). Levels outside this range will be clamped. Ignored by the `tar` format.
const Core_file_compress_v1_Input_level core.InputId = "level"
// A list of file or directory paths to include in the archive. Directories are scanned recursively. Symbolic links are ignored.
const Core_file_compress_v1_Input_paths core.InputId = "paths"

// Outputs (o) ==> 

// The binary data stream of the compressed archive.
const Core_file_compress_v1_Output_data core.OutputId = "data"
// Triggered if an error occurs during compression.
const Core_file_compress_v1_Output_exec_err core.OutputId = "exec-err"
// Triggered when compression is successful.
const Core_file_compress_v1_Output_exec_success core.OutputId = "exec-success"
// The file extension of the archive (e.g., .zip, .tar, .tar.gz).
const Core_file_compress_v1_Output_suffix core.OutputId = "suffix"
