// Code generated by actrun. DO NOT EDIT.

package node_interfaces

import "github.com/actionforge/actrun-cli/core" // Finds a relative path from a base path to a target path.

// ==> (o) Inputs

// The base path to measure from.
const Core_filepath_rel_v1_Input_basepath core.InputId = "basepath"
// The target path to measure to.
const Core_filepath_rel_v1_Input_targpath core.InputId = "targpath"

// Outputs (o) ==> 

// The relative path from basepath to targpath.
const Core_filepath_rel_v1_Output_result core.OutputId = "result"
