// Code generated by actrun. DO NOT EDIT.

package node_interfaces

import "github.com/actionforge/actrun-cli/core" // Negate the input. Input must be of type *array*, *string*, *number*, or *bool*. Any other input type will result in an error during runtime.

// ==> (o) Inputs

// Input value to negate.
const Core_negate_v1_Input_input core.InputId = "input"

// Outputs (o) ==> 

// Negated value of the input.
const Core_negate_v1_Output_result core.OutputId = "result"
