// Code generated by actrun. DO NOT EDIT.

package node_interfaces

import "github.com/actionforge/actrun-cli/core" // Clones a Git repository from a URL into a local directory.

// ==> (o) Inputs

// Optional credentials for accessing private repositories. If not provided, the node will use the default Git configuration.
const Core_git_clone_v1_Input_auth core.InputId = "auth"
// Whether to checkout the specified reference after cloning. Defaults to true.
const Core_git_clone_v1_Input_checkout core.InputId = "checkout"
// Creates a shallow clone with a history truncated to the specified number of commits. A value of 0 or less means a full clone.
const Core_git_clone_v1_Input_depth core.InputId = "depth"
// The local directory path where the repository will be cloned.
const Core_git_clone_v1_Input_directory core.InputId = "directory"
const Core_git_clone_v1_Input_exec core.InputId = "exec"
// If true, only the specified reference will be cloned (no other branches or tags).
const Core_git_clone_v1_Input_only_ref core.InputId = "only_ref"
// The specific branch to clone. If empty, the remote's default branch is used.
const Core_git_clone_v1_Input_ref core.InputId = "ref"
// The URL of the Git repository to clone (e.g., https, ssh).
const Core_git_clone_v1_Input_url core.InputId = "url"

// Outputs (o) ==> 

// Executes if the clone operation fails.
const Core_git_clone_v1_Output_exec_err core.OutputId = "exec-err"
// Executes if the clone operation is successful.
const Core_git_clone_v1_Output_exec_success core.OutputId = "exec-success"
// The cloned Git repository object.
const Core_git_clone_v1_Output_repo core.OutputId = "repo"
