// Code generated by actrun. DO NOT EDIT.

package node_interfaces

import "github.com/actionforge/actrun-cli/core" // Syncs files from a Perforce P4 depot path.

// ==> (o) Inputs

// The Perforce workspace name. Overrides the value from credentials or P4CLIENT env var.
const Core_p4_sync_v1_Input_client core.InputId = "client"
// Optional P4 credentials. If not provided, falls back to P4PORT/P4USER/P4PASSWD environment variables.
const Core_p4_sync_v1_Input_credentials core.InputId = "credentials"
// The Perforce depot path to sync (e.g. //depot/project/...).
const Core_p4_sync_v1_Input_depot_path core.InputId = "depot_path"
const Core_p4_sync_v1_Input_exec core.InputId = "exec"
// If true, forces the sync (-f flag), re-downloading all files regardless of have list.
const Core_p4_sync_v1_Input_force core.InputId = "force"

// Outputs (o) ==> 

// Executes if there is an error during sync.
const Core_p4_sync_v1_Output_exec_err core.OutputId = "exec-err"
// Executes if the sync operation is successful.
const Core_p4_sync_v1_Output_exec_success core.OutputId = "exec-success"
// The stdout/stderr output from the p4 sync command.
const Core_p4_sync_v1_Output_output core.OutputId = "output"
