// Code generated by actrun. DO NOT EDIT.

package node_interfaces

import "github.com/actionforge/actrun-cli/core" // Print something to the console

// ==> (o) Inputs

const Core_print_v1_Input_color core.InputId = "color"
const Core_print_v1_Input_exec core.InputId = "exec"
const Core_print_v1_Input_values core.InputId = "values"

// Outputs (o) ==> 

const Core_print_v1_Output_exec core.OutputId = "exec"
