// Code generated by actrun. DO NOT EDIT.

package node_interfaces

import "github.com/actionforge/actrun-cli/core" // Matches a string against a regex pattern and returns the captured groups.

// ==> (o) Inputs

// The string to match against the regex pattern
const Core_string_match_regex_v1_Input_input core.InputId = "input"
// The regex pattern to match
const Core_string_match_regex_v1_Input_pattern core.InputId = "pattern"

// Outputs (o) ==> 

// Captured groups from the regex match
const Core_string_match_regex_v1_Output_groups core.OutputId = "groups"
