// Code generated by actrun. DO NOT EDIT.

package node_interfaces

import "github.com/actionforge/actrun-cli/core" // Switches branches or restores working tree files.

// ==> (o) Inputs

// If true, creates a new branch named after the 'Reference' input.
const Core_git_checkout_v1_Input_create core.InputId = "create"
const Core_git_checkout_v1_Input_exec core.InputId = "exec"
// If true, forces the checkout, discarding any local changes in the working directory. Use with caution.
const Core_git_checkout_v1_Input_force core.InputId = "force"
// The name of the branch, tag, or the commit hash to check out.
const Core_git_checkout_v1_Input_reference core.InputId = "reference"
// The Git repository object from a clone or open node.
const Core_git_checkout_v1_Input_repo core.InputId = "repo"

// Outputs (o) ==> 

// Executes if there is an error during checkout.
const Core_git_checkout_v1_Output_exec_err core.OutputId = "exec-err"
// Executes if the checkout operation is successful.
const Core_git_checkout_v1_Output_exec_success core.OutputId = "exec-success"
