// Code generated by actrun. DO NOT EDIT.

package node_interfaces

import "github.com/actionforge/actrun-cli/core" // Node to terminate the current program with a specified exit code.

// ==> (o) Inputs

// The exit code to terminate the program with.
const Core_process_exit_v1_Input_code core.InputId = "code"
const Core_process_exit_v1_Input_exec core.InputId = "exec"
