// Code generated by actrun. DO NOT EDIT.

package node_interfaces

import "github.com/actionforge/actrun-cli/core" // A node to read key secrets.

// ==> (o) Inputs

// The name of the secret.
const Core_secret_v1_Input_name core.InputId = "name"
// A prefix for the secret, specifically used to easier construct environment variables.
const Core_secret_v1_Input_prefix core.InputId = "prefix"

// Outputs (o) ==> 

// The value of the secret.
const Core_secret_v1_Output_secret core.OutputId = "secret"
