// Code generated by actrun. DO NOT EDIT.

package node_interfaces

import "github.com/actionforge/actrun-cli/core" // Creates a credential object containing SSH private key data.

// ==> (o) Inputs

// The file path to the key. It supports RSA (PKCS#1), PKCS#8, DSA (OpenSSL), and ECDSA private keys
const Core_credentials_ssh_v1_Input_private_key core.InputId = "private_key"
// The password for the private key, if it is encrypted.
const Core_credentials_ssh_v1_Input_private_key_password core.InputId = "private_key_password"
// The username to use for SSH authentication, e.g. `git` or `ubuntu`.
const Core_credentials_ssh_v1_Input_username core.InputId = "username"

// Outputs (o) ==> 

// A credential object containing the private key data.
const Core_credentials_ssh_v1_Output_credential core.OutputId = "credential"
