// Code generated by actrun. DO NOT EDIT.

package node_interfaces

import "github.com/actionforge/actrun-cli/core" // Node to make http requests. The node is fully executed after the response header is received. The http connection is kept open until the response body stream is fully read or somehow closed.

// ==> (o) Inputs

// Optional body to send with the request.
const Core_http_v1_Input_body core.InputId = "body"
const Core_http_v1_Input_exec core.InputId = "exec"
// Optional headers to send with the request.
const Core_http_v1_Input_header core.InputId = "header"
// The http method to use for the request.
const Core_http_v1_Input_method core.InputId = "method"
// The URL to make the request to. Must start with `http://` or `https://`.
const Core_http_v1_Input_url core.InputId = "url"

// Outputs (o) ==> 

// The response body.
const Core_http_v1_Output_body core.OutputId = "body"
// The http request was successful. The status code is **not** 2xx.
const Core_http_v1_Output_exec_err core.OutputId = "exec-err"
// The http request was successful. The status code **is** 2xx.
const Core_http_v1_Output_exec_success core.OutputId = "exec-success"
// The status code of the response.
const Core_http_v1_Output_status_code core.OutputId = "status_code"
