// Code generated by actrun. DO NOT EDIT.

package node_interfaces

import "github.com/actionforge/actrun-cli/core" // Encode a UTF-8 string into various string-based formats like Base64, Hex, UTF-16, and UTF-32.

// ==> (o) Inputs

// The UTF-8 string to encode.
const Core_string_encode_v1_Input_input core.InputId = "input"
// The encoding operation to apply.
const Core_string_encode_v1_Input_op core.InputId = "op"

// Outputs (o) ==> 

// The resulting encoded string.
const Core_string_encode_v1_Output_result core.OutputId = "result"
