// Code generated by actrun. DO NOT EDIT.

package node_interfaces

import "github.com/actionforge/actrun-cli/core" // Select a specific value from a list of choices.

// ==> (o) Inputs

// A list of inputs to select from. The first port starts at index 0.
const Core_select_data_v1_Input_choices core.InputId = "choices"
// The index position of the value to select. Must be 0 or greater. An index out of bounds will result in a runtime error.
const Core_select_data_v1_Input_index core.InputId = "index"

// Outputs (o) ==> 

// The selected value.
const Core_select_data_v1_Output_value core.OutputId = "value"
