// Code generated by actrun. DO NOT EDIT.

package node_interfaces

import "github.com/actionforge/actrun-cli/core" // Creates a random stream based on user-defined character set preferences.

// ==> (o) Inputs

// Triggers the generation of the stream.
const Core_random_stream_v1_Input_exec core.InputId = "exec"
// Include lower-case characters (a-z) in the stream.
const Core_random_stream_v1_Input_include_characters core.InputId = "include_characters"
// Include numbers (0-9) in the stream.
const Core_random_stream_v1_Input_include_numbers core.InputId = "include_numbers"
// Include special characters (!@#$%^&*() etc.) in the stream.
const Core_random_stream_v1_Input_include_special core.InputId = "include_special"
// Include upper-case characters (A-Z) in the stream.
const Core_random_stream_v1_Input_include_uppercase core.InputId = "include_uppercase"
// The length of the stream.
const Core_random_stream_v1_Input_length core.InputId = "length"
// The seed for the random number generator (-1 for true randomness)
const Core_random_stream_v1_Input_seed core.InputId = "seed"

// Outputs (o) ==> 

// Triggered when the stream is successfully created.
const Core_random_stream_v1_Output_exec_success core.OutputId = "exec-success"
// The generated random stream
const Core_random_stream_v1_Output_stream core.OutputId = "stream"
