// Code generated by actrun. DO NOT EDIT.

package node_interfaces

import "github.com/actionforge/actrun-cli/core" // Creates a new commit from the staged changes.

// ==> (o) Inputs

// The email of the commit author. Overrides the repository's config.
const Core_git_commit_v1_Input_author_email core.InputId = "author_email"
// The name of the commit author. Overrides the repository's config.
const Core_git_commit_v1_Input_author_name core.InputId = "author_name"
const Core_git_commit_v1_Input_exec core.InputId = "exec"
// The commit message.
const Core_git_commit_v1_Input_message core.InputId = "message"
// The Git repository object from a clone or open node.
const Core_git_commit_v1_Input_repo core.InputId = "repo"
// Whether to stage all changes before committing.
const Core_git_commit_v1_Input_stage core.InputId = "stage"

// Outputs (o) ==> 

// The full hash of the newly created commit.
const Core_git_commit_v1_Output_commit_hash core.OutputId = "commit_hash"
// Executes if there is an error during the commit.
const Core_git_commit_v1_Output_exec_err core.OutputId = "exec-err"
// Executes if the commit is created successfully.
const Core_git_commit_v1_Output_exec_success core.OutputId = "exec-success"
