// Code generated by actrun. DO NOT EDIT.

package node_interfaces

import "github.com/actionforge/actrun-cli/core" // Comment node

// ==> (o) Inputs

const Core_comment_v1_Input_markdown core.InputId = "markdown"
