// Code generated by actrun. DO NOT EDIT.

package node_interfaces

import "github.com/actionforge/actrun-cli/core" // Run a Docker container from an image or Dockerfile.

// ==> (o) Inputs

// Arguments to pass to the container entrypoint.
const Core_docker_run_v1_Input_args core.InputId = "args"
// Override the default entrypoint of the container.
const Core_docker_run_v1_Input_entrypoint core.InputId = "entrypoint"
// Environment variables to pass to the container.
const Core_docker_run_v1_Input_env core.InputId = "env"
const Core_docker_run_v1_Input_exec core.InputId = "exec"
// Docker image URL or Dockerfile path.
const Core_docker_run_v1_Input_image core.InputId = "image"
// Docker network to connect the container to.
const Core_docker_run_v1_Input_network core.InputId = "network"
// When to pull the image from the registry.
const Core_docker_run_v1_Input_pull core.InputId = "pull"
// Mount the host's Docker socket into the container, enabling Docker-in-Docker.
const Core_docker_run_v1_Input_docker_socket core.InputId = "docker_socket"
// Volume mounts in the format host_path:container_path.
const Core_docker_run_v1_Input_volumes core.InputId = "volumes"
// Working directory inside the container.
const Core_docker_run_v1_Input_workdir core.InputId = "workdir"

// Outputs (o) ==>

const Core_docker_run_v1_Output_exec_err core.OutputId = "exec-err"
const Core_docker_run_v1_Output_exec_success core.OutputId = "exec-success"
const Core_docker_run_v1_Output_exit_code core.OutputId = "exit_code"
