// Code generated by actrun. DO NOT EDIT.

package node_interfaces

import "github.com/actionforge/actrun-cli/core" // Perform a join operation on a string.

// ==> (o) Inputs

// The delimiter to use between the segments.
const Core_string_join_v1_Input_delimiter core.InputId = "delimiter"
// The segments of the string to join.
const Core_string_join_v1_Input_segments core.InputId = "segments"

// Outputs (o) ==> 

// The joined string.
const Core_string_join_v1_Output_result core.OutputId = "result"
