// Code generated by actrun. DO NOT EDIT.

package node_interfaces

import "github.com/actionforge/actrun-cli/core" // Parse JSON, YAML, TOML, INI, and other formats.

// ==> (o) Inputs

const Core_parser_v1_Input_exec core.InputId = "exec"
const Core_parser_v1_Input_format core.InputId = "format"
const Core_parser_v1_Input_input core.InputId = "input"

// Outputs (o) ==> 

const Core_parser_v1_Output_exec_err core.OutputId = "exec-err"
const Core_parser_v1_Output_exec_success core.OutputId = "exec-success"
// The parsed object.

const Core_parser_v1_Output_object core.OutputId = "object"
