// Code generated by actrun. DO NOT EDIT.

package node_interfaces

import "github.com/actionforge/actrun-cli/core" // This node takes an array of strings and joins them together to form a single filepath.

// ==> (o) Inputs

// The segments of the path to join.
const Core_filepath_join_array_v1_Input_segments core.InputId = "segments"

// Outputs (o) ==> 

// The joined path.
const Core_filepath_join_array_v1_Output_result core.OutputId = "result"
