// Code generated by actrun. DO NOT EDIT.

package node_interfaces

import "github.com/actionforge/actrun-cli/core" // Provides information about the system.

// Outputs (o) ==> 

// The architecture index. `0` for x64 and `1` for arm64.
const Core_system_info_v1_Output_arch_index core.OutputId = "arch_index"
// The architecture string. Either `x64` or `arm64`.
const Core_system_info_v1_Output_arch_string core.OutputId = "arch_string"
// Returns the number of logical CPUs usable by the current process. The set of available CPUs is checked by querying the operating system at process startup. Changes to operating system CPU allocation after process startup are not reflected.
const Core_system_info_v1_Output_cpu_count core.OutputId = "cpu_count"
// `true` if the architecture is arm64.
const Core_system_info_v1_Output_is_arm64 core.OutputId = "is_arm64"
// `true` if the platform is Linux.
const Core_system_info_v1_Output_is_linux core.OutputId = "is_linux"
// `true` if the platform is MacOS.
const Core_system_info_v1_Output_is_macos core.OutputId = "is_macos"
// `true` if the platform is Windows.
const Core_system_info_v1_Output_is_win core.OutputId = "is_win"
// `true` if the architecture is x64.
const Core_system_info_v1_Output_is_x64 core.OutputId = "is_x64"
// The platform index. `0` for Windows, `1` for MacOS, and `2` for Linux.
const Core_system_info_v1_Output_platform_index core.OutputId = "platform_index"
// The platform string. Either `windows`, `macos`, or `linux`.
const Core_system_info_v1_Output_platform_string core.OutputId = "platform_string"
