// Code generated by actrun. DO NOT EDIT.

package node_interfaces

import "github.com/actionforge/actrun-cli/core" // Retrieve a value from a parsed JSON, YAML, TOML or INI object. Usually data comes from [Parser](./../parser/v1.md) in order to extract a value from the parsed object.

// ==> (o) Inputs

const Core_property_getter_v1_Input_exec core.InputId = "exec"
// The object to extract the value from.
const Core_property_getter_v1_Input_object core.InputId = "object"
// The property path to extract the value from. See [Property Path](./../../../reference/property-paths.md) for more info.
const Core_property_getter_v1_Input_path core.InputId = "path"

// Outputs (o) ==> 

const Core_property_getter_v1_Output_exec_err core.OutputId = "exec-err"
const Core_property_getter_v1_Output_exec_success core.OutputId = "exec-success"
const Core_property_getter_v1_Output_found core.OutputId = "found"
// The extracted object.
const Core_property_getter_v1_Output_value core.OutputId = "value"
