// Code generated by actrun. DO NOT EDIT.

package node_interfaces

import "github.com/actionforge/actrun-cli/core" // Updates remote refs along with associated objects.

// ==> (o) Inputs

// Optional credentials for accessing private repositories. If not provided, the node will use the default Git configuration.
const Core_git_push_v1_Input_auth core.InputId = "auth"
// The branch to push. If empty, the current branch is used.
const Core_git_push_v1_Input_branch core.InputId = "branch"
const Core_git_push_v1_Input_exec core.InputId = "exec"
// Whether to force the push (use with caution). Defaults to false.
const Core_git_push_v1_Input_force core.InputId = "force"
// The name of the remote repository to push to. Defaults to 'origin'.
const Core_git_push_v1_Input_remote core.InputId = "remote"
// The Git repository object from a clone or open node.
const Core_git_push_v1_Input_repo core.InputId = "repo"
// Whether to push local tags to the remote. Defaults to false.
const Core_git_push_v1_Input_tags core.InputId = "tags"

// Outputs (o) ==> 

// Executes if there is an error during the push.
const Core_git_push_v1_Output_exec_err core.OutputId = "exec-err"
// Executes if the push operation is successful.
const Core_git_push_v1_Output_exec_success core.OutputId = "exec-success"
