// Code generated by actrun. DO NOT EDIT.

package node_interfaces

import "github.com/actionforge/actrun-cli/core" // Constant value of a bool.

// ==> (o) Inputs

const Core_const_bool_v1_Input_value core.InputId = "value"

// Outputs (o) ==> 

const Core_const_bool_v1_Output_result core.OutputId = "result"
