// Code generated by actrun. DO NOT EDIT.

package node_interfaces

import "github.com/actionforge/actrun-cli/core" // Cache a stream and output it as a string.

// ==> (o) Inputs

// The input stream to be cached.
const Core_stream_cache_v1_Input_stream core.InputId = "stream"

// Outputs (o) ==> 

// The cached stream as a string.
const Core_stream_cache_v1_Output_result core.OutputId = "result"
