// Code generated by actrun. DO NOT EDIT.

package node_interfaces

import "github.com/actionforge/actrun-cli/core" // Downloads a file from the Perforce P4 depot without requiring a workspace.

// ==> (o) Inputs

// Optional P4 credentials. If not provided, falls back to P4 environment variables.
const Core_p4_print_v1_Input_credentials core.InputId = "credentials"
// The depot path of the file to download.
const Core_p4_print_v1_Input_depot_path core.InputId = "depot_path"
const Core_p4_print_v1_Input_exec core.InputId = "exec"
// The local file path where the downloaded file will be saved.
const Core_p4_print_v1_Input_output_path core.InputId = "output_path"

// Outputs (o) ==> 

// Executes if there is an error downloading the file.
const Core_p4_print_v1_Output_exec_err core.OutputId = "exec-err"
// Executes if the file is downloaded successfully.
const Core_p4_print_v1_Output_exec_success core.OutputId = "exec-success"
