// Code generated by actrun. DO NOT EDIT.

package node_interfaces

import "github.com/actionforge/actrun-cli/core" // Github Action

// ==> (o) Inputs

const Core_gh_action_v1_Input_env core.InputId = "env"

// Outputs (o) ==> 

const Core_gh_action_v1_Output_exec_err core.OutputId = "exec-err"
const Core_gh_action_v1_Output_exec_success core.OutputId = "exec-success"
