// Code generated by actrun. DO NOT EDIT.

package node_interfaces

import "github.com/actionforge/actrun-cli/core" // Returns the length of the input.

// ==> (o) Inputs

// The input to get the length of.
const Core_length_v1_Input_input core.InputId = "input"

// Outputs (o) ==> 

const Core_length_v1_Output_result core.OutputId = "result"
