// Code generated by actrun. DO NOT EDIT.

package node_interfaces

import "github.com/actionforge/actrun-cli/core" // Replaces occurrences of a substring within a string based on selected criteria.

// ==> (o) Inputs

// The string to perform the replacement on
const Core_string_replace_v1_Input_input core.InputId = "input"
// Type
const Core_string_replace_v1_Input_op core.InputId = "op"
// The string to replace the target with
const Core_string_replace_v1_Input_replacement core.InputId = "replacement"
// The substring or regex pattern to replace
const Core_string_replace_v1_Input_substring core.InputId = "substring"

// Outputs (o) ==> 

// Output string after replacement
const Core_string_replace_v1_Output_result core.OutputId = "result"
