// Code generated by actrun. DO NOT EDIT.

package node_interfaces

import "github.com/actionforge/actrun-cli/core" // Decompresses an archive stream to a directory.

// ==> (o) Inputs

// The binary data stream of the archive to decompress.
const Core_file_decompress_v1_Input_data core.InputId = "data"
// The target directory where files will be extracted. Created automatically if it does not exist. Relative paths are resolved from the current working directory.
const Core_file_decompress_v1_Input_dest_path core.InputId = "dest_path"
// Starts the decompression process.
const Core_file_decompress_v1_Input_exec core.InputId = "exec"
const Core_file_decompress_v1_Input_format core.InputId = "format"

// Outputs (o) ==> 

// Triggered if an error occurs during decompression.
const Core_file_decompress_v1_Output_exec_err core.OutputId = "exec-err"
// Triggered when decompression is successful.
const Core_file_decompress_v1_Output_exec_success core.OutputId = "exec-success"
// A list of absolute file paths that were extracted.
const Core_file_decompress_v1_Output_files core.OutputId = "files"
