// Code generated by actrun. DO NOT EDIT.

package node_interfaces

import "github.com/actionforge/actrun-cli/core" // Transform and manipulate strings using various casing styles and trimming or reversing operations.

// ==> (o) Inputs

// String to transform
const Core_string_transform_v1_Input_input core.InputId = "input"
// Transformation operation to apply
const Core_string_transform_v1_Input_op core.InputId = "op"

// Outputs (o) ==> 

// Transformed string
const Core_string_transform_v1_Output_result core.OutputId = "result"
