// Code generated by actrun. DO NOT EDIT.

package node_interfaces

import "github.com/actionforge/actrun-cli/core" // Evaluates the 'truthiness' of an input value, returning `true` or `false`.

// ==> (o) Inputs

// The value to be evaluated.
const Core_affirm_v1_Input_input core.InputId = "input"

// Outputs (o) ==> 

// The boolean result.
const Core_affirm_v1_Output_result core.OutputId = "result"
