// Code generated by actrun. DO NOT EDIT.

package node_interfaces

import "github.com/actionforge/actrun-cli/core" // A node that kicks off a GitHub Actions workflow.

// Outputs (o) ==> 

// Execute actions when a branch protection rule is triggered
const Core_gh_start_v1_Output_exec_on_branch_protection_rule core.OutputId = "exec-on_branch_protection_rule"
// Execute actions when a check run is triggered
const Core_gh_start_v1_Output_exec_on_check_run core.OutputId = "exec-on_check_run"
// Execute actions when a check suite is triggered
const Core_gh_start_v1_Output_exec_on_check_suite core.OutputId = "exec-on_check_suite"
// Execute actions when a new resource is created
const Core_gh_start_v1_Output_exec_on_create core.OutputId = "exec-on_create"
// Execute actions when a resource is deleted
const Core_gh_start_v1_Output_exec_on_delete core.OutputId = "exec-on_delete"
// Execute actions when a deployment is triggered
const Core_gh_start_v1_Output_exec_on_deployment core.OutputId = "exec-on_deployment"
// Execute actions when a deployment status is triggered
const Core_gh_start_v1_Output_exec_on_deployment_status core.OutputId = "exec-on_deployment_status"
// Execute actions when a discussion is triggered
const Core_gh_start_v1_Output_exec_on_discussion core.OutputId = "exec-on_discussion"
// Execute actions when a discussion comment is triggered
const Core_gh_start_v1_Output_exec_on_discussion_comment core.OutputId = "exec-on_discussion_comment"
// Execute actions when a repository is forked
const Core_gh_start_v1_Output_exec_on_fork core.OutputId = "exec-on_fork"
// Execute actions when a Gollum event is triggered
const Core_gh_start_v1_Output_exec_on_gollum core.OutputId = "exec-on_gollum"
// Execute actions when an issue comment is triggered
const Core_gh_start_v1_Output_exec_on_issue_comment core.OutputId = "exec-on_issue_comment"
// Execute actions when an issue is triggered
const Core_gh_start_v1_Output_exec_on_issues core.OutputId = "exec-on_issues"
// Execute actions when a label is triggered
const Core_gh_start_v1_Output_exec_on_label core.OutputId = "exec-on_label"
// Execute actions when a merge group is triggered
const Core_gh_start_v1_Output_exec_on_merge_group core.OutputId = "exec-on_merge_group"
// Execute actions when a milestone is triggered
const Core_gh_start_v1_Output_exec_on_milestone core.OutputId = "exec-on_milestone"
// Execute actions when a page build is triggered
const Core_gh_start_v1_Output_exec_on_page_build core.OutputId = "exec-on_page_build"
// Execute actions when a project is triggered
const Core_gh_start_v1_Output_exec_on_project core.OutputId = "exec-on_project"
// Execute actions when a project card is triggered
const Core_gh_start_v1_Output_exec_on_project_card core.OutputId = "exec-on_project_card"
// Execute actions when a project column is triggered
const Core_gh_start_v1_Output_exec_on_project_column core.OutputId = "exec-on_project_column"
// Execute actions when a repository is made public
const Core_gh_start_v1_Output_exec_on_public core.OutputId = "exec-on_public"
// Execute actions when a pull request is triggered
const Core_gh_start_v1_Output_exec_on_pull_request core.OutputId = "exec-on_pull_request"
// Execute actions when a pull request comment is triggered
const Core_gh_start_v1_Output_exec_on_pull_request_comment core.OutputId = "exec-on_pull_request_comment"
// Execute actions when a pull request review is triggered
const Core_gh_start_v1_Output_exec_on_pull_request_review core.OutputId = "exec-on_pull_request_review"
// Execute actions when a pull request review comment is triggered
const Core_gh_start_v1_Output_exec_on_pull_request_review_comment core.OutputId = "exec-on_pull_request_review_comment"
// Execute actions when a pull request target is triggered
const Core_gh_start_v1_Output_exec_on_pull_request_target core.OutputId = "exec-on_pull_request_target"
// Execute actions when a push event is triggered
const Core_gh_start_v1_Output_exec_on_push core.OutputId = "exec-on_push"
// Execute actions when a registry package is triggered
const Core_gh_start_v1_Output_exec_on_registry_package core.OutputId = "exec-on_registry_package"
// Execute actions when a release is triggered
const Core_gh_start_v1_Output_exec_on_release core.OutputId = "exec-on_release"
// Execute actions when a repository dispatch is triggered
const Core_gh_start_v1_Output_exec_on_repository_dispatch core.OutputId = "exec-on_repository_dispatch"
// Execute actions when a scheduled event is triggered
const Core_gh_start_v1_Output_exec_on_schedule core.OutputId = "exec-on_schedule"
// Execute actions when a status is triggered
const Core_gh_start_v1_Output_exec_on_status core.OutputId = "exec-on_status"
// Execute actions when a repository is watched
const Core_gh_start_v1_Output_exec_on_watch core.OutputId = "exec-on_watch"
// Execute actions when a workflow call is triggered
const Core_gh_start_v1_Output_exec_on_workflow_call core.OutputId = "exec-on_workflow_call"
// Execute actions when a workflow dispatch is triggered
const Core_gh_start_v1_Output_exec_on_workflow_dispatch core.OutputId = "exec-on_workflow_dispatch"
// Execute actions when a workflow run is triggered
const Core_gh_start_v1_Output_exec_on_workflow_run core.OutputId = "exec-on_workflow_run"
