// Code generated by actrun. DO NOT EDIT.

package node_interfaces

import "github.com/actionforge/actrun-cli/core" // Read a file from the file system via a lstream.

// ==> (o) Inputs

const Core_file_read_v1_Input_exec core.InputId = "exec"
// The path to the file to read.
const Core_file_read_v1_Input_path core.InputId = "path"

// Outputs (o) ==> 

// A data stream of the file's content.
const Core_file_read_v1_Output_data core.OutputId = "data"
const Core_file_read_v1_Output_exec_err core.OutputId = "exec-err"
const Core_file_read_v1_Output_exec_success core.OutputId = "exec-success"
const Core_file_read_v1_Output_exists core.OutputId = "exists"
