// Code generated by actrun. DO NOT EDIT.

package node_interfaces

import "github.com/actionforge/actrun-cli/core" // Write a file to the file system.

// ==> (o) Inputs

const Core_file_write_v1_Input_data core.InputId = "data"
const Core_file_write_v1_Input_exec core.InputId = "exec"
const Core_file_write_v1_Input_path core.InputId = "path"

// Outputs (o) ==> 

const Core_file_write_v1_Output_exec_err core.OutputId = "exec-err"
const Core_file_write_v1_Output_exec_success core.OutputId = "exec-success"
