// Code generated by actrun. DO NOT EDIT.

package node_interfaces

import "github.com/actionforge/actrun-cli/core" // Runs an arbitrary Perforce P4 command.

// ==> (o) Inputs

// Additional arguments for the p4 command.
const Core_p4_run_v1_Input_args core.InputId = "args"
// The p4 subcommand to run (e.g. files, changes, describe, client).
const Core_p4_run_v1_Input_command core.InputId = "command"
// Optional P4 credentials. If not provided, falls back to P4 environment variables.
const Core_p4_run_v1_Input_credentials core.InputId = "credentials"
const Core_p4_run_v1_Input_exec core.InputId = "exec"

// Outputs (o) ==> 

// Executes if the command fails (non-zero exit code).
const Core_p4_run_v1_Output_exec_err core.OutputId = "exec-err"
// Executes if the command succeeds (exit code 0).
const Core_p4_run_v1_Output_exec_success core.OutputId = "exec-success"
// The exit code of the p4 command.
const Core_p4_run_v1_Output_exit_code core.OutputId = "exit_code"
// The combined stdout/stderr output from the p4 command.
const Core_p4_run_v1_Output_output core.OutputId = "output"
