// Code generated by actrun. DO NOT EDIT.

package node_interfaces

import "github.com/actionforge/actrun-cli/core" // Apply the `Xand` operator on two or more boolean values.

// ==> (o) Inputs

// The boolean values to apply the `AND` operator on.
const Core_bool_xand_v1_Input_inputs core.InputId = "inputs"

// Outputs (o) ==> 

// The result of the boolean operation. `true` if all input values are `true`, `false` otherwise.
const Core_bool_xand_v1_Output_result core.OutputId = "result"
