// Code generated by actrun. DO NOT EDIT.

package node_interfaces

import "github.com/actionforge/actrun-cli/core" // Gets the value of an environment variable by its name.

// ==> (o) Inputs

// The name of the environment variable to get.
const Core_env_get_v1_Input_env core.InputId = "env"

// Outputs (o) ==> 

// The value of the environment variable. Returns an empty string if not found.
const Core_env_get_v1_Output_env core.OutputId = "env"
