// Code generated by actrun. DO NOT EDIT.

package node_interfaces

import "github.com/actionforge/actrun-cli/core" // Computes a cryptographic hash for the given input.

// ==> (o) Inputs

// The hash algorithm to use.
const Core_hash_v1_Input_algorithm core.InputId = "algorithm"
// Triggers the hashing process.
const Core_hash_v1_Input_exec core.InputId = "exec"
// The input data stream to hash.
const Core_hash_v1_Input_input core.InputId = "input"

// Outputs (o) ==> 

// There was an error during the hashing process.
const Core_hash_v1_Output_exec_err core.OutputId = "exec-err"
// The hashing process completed successfully.
const Core_hash_v1_Output_exec_success core.OutputId = "exec-success"
// The computed hash as a hexadecimal string.
const Core_hash_v1_Output_hash core.OutputId = "hash"
