// Code generated by actrun. DO NOT EDIT.

package node_interfaces

import "github.com/actionforge/actrun-cli/core" // Calculate the modulo of two numbers.

// ==> (o) Inputs

// The first number.
const Core_math_modulo_v1_Input_op1 core.InputId = "op1"
// The second number.
const Core_math_modulo_v1_Input_op2 core.InputId = "op2"

// Outputs (o) ==> 

// The result of the modulo calculation.
const Core_math_modulo_v1_Output_result core.OutputId = "result"
