// Code generated by actrun. DO NOT EDIT.

package node_interfaces

import "github.com/actionforge/actrun-cli/core" // The Architecture Switch node allows to change the execution flow based on the architecture of the system.

// ==> (o) Inputs

const Core_switch_arch_v1_Input_exec core.InputId = "exec"

// Outputs (o) ==> 

// Executes the arm64 architecture branch.
const Core_switch_arch_v1_Output_exec_arm64 core.OutputId = "exec-arm64"
// Executes the x64 architecture branch.
const Core_switch_arch_v1_Output_exec_x64 core.OutputId = "exec-x64"
