// Code generated by actrun. DO NOT EDIT.

package node_interfaces

import "github.com/actionforge/actrun-cli/core" // Perform basic arithmetic operations.

// ==> (o) Inputs

// The first number.
const Core_math_op_v1_Input_op1 core.InputId = "op1"
// The second number.
const Core_math_op_v1_Input_op2 core.InputId = "op2"
// The arithmetic operator to use.
const Core_math_op_v1_Input_operator core.InputId = "operator"

// Outputs (o) ==> 

// The result of the arithmetic operation.
const Core_math_op_v1_Output_result core.OutputId = "result"
