// Code generated by actrun. DO NOT EDIT.

package node_interfaces

import "github.com/actionforge/actrun-cli/core" // Generates a random number based on user-defined range and seed. Can be used as well for boolean values by setting the minimum and maximum values to 0 and 1 respectively.

// ==> (o) Inputs

// Triggers the generation of the random number.
const Core_random_number_v1_Input_exec core.InputId = "exec"
// The maximum value of the random number
const Core_random_number_v1_Input_max core.InputId = "max"
// The minimum value of the random number
const Core_random_number_v1_Input_min core.InputId = "min"
// The seed for the random number generator (-1 for true randomness)
const Core_random_number_v1_Input_seed core.InputId = "seed"

// Outputs (o) ==> 

// Triggered when the random number is successfully generated.
const Core_random_number_v1_Output_exec_success core.OutputId = "exec-success"
// The generated random number
const Core_random_number_v1_Output_number core.OutputId = "number"
