// Code generated by actrun. DO NOT EDIT.

package node_interfaces

import "github.com/actionforge/actrun-cli/core" // Iterators are a way to walk through an array or map.

// ==> (o) Inputs

// Executes the loop.
const Core_for_each_loop_v1_Input_exec core.InputId = "exec"
// Breaks the loop.
const Core_for_each_loop_v1_Input_exec_break core.InputId = "exec-break"
const Core_for_each_loop_v1_Input_input core.InputId = "input"

// Outputs (o) ==> 

const Core_for_each_loop_v1_Output_exec_body core.OutputId = "exec-body"
const Core_for_each_loop_v1_Output_exec_completed core.OutputId = "exec-completed"
// A number index or key of a map.
const Core_for_each_loop_v1_Output_key core.OutputId = "key"
// The value of the item
const Core_for_each_loop_v1_Output_value core.OutputId = "value"
