// Code generated by actrun. DO NOT EDIT.

package node_interfaces

import "github.com/actionforge/actrun-cli/core" // Download files from a repo on the orchestrator and write them to disk.

// ==> (o) Inputs

const Core_repo_download_v1_Input_exec core.InputId = "exec"
// File paths within the repo to download. Each file is written to the same relative path on disk.
const Core_repo_download_v1_Input_paths core.InputId = "paths"

// Outputs (o) ==>

const Core_repo_download_v1_Output_exec_err core.OutputId = "exec-err"
const Core_repo_download_v1_Output_exec_success core.OutputId = "exec-success"
