// Code generated by actrun. DO NOT EDIT.

package node_interfaces

import "github.com/actionforge/actrun-cli/core" // Pauses the execution for a specified duration. This node does not block or pause the entire workflow, only the current execution path.

// ==> (o) Inputs

// The amount of time to sleep
const Core_sleep_v1_Input_duration core.InputId = "duration"
const Core_sleep_v1_Input_exec core.InputId = "exec"
// The time unit for the duration (seconds, milliseconds, microseconds, nanoseconds)
const Core_sleep_v1_Input_unit core.InputId = "unit"

// Outputs (o) ==> 

// Executes the next node after the sleep duration
const Core_sleep_v1_Output_exec core.OutputId = "exec"
