// Code generated by actrun. DO NOT EDIT.

package node_interfaces

import "github.com/actionforge/actrun-cli/core" // Perform a join operation on a file path

// ==> (o) Inputs

// The segments of the path to join.
const Core_filepath_join_v1_Input_segments core.InputId = "segments"

// Outputs (o) ==> 

// The joined path.
const Core_filepath_join_v1_Output_result core.OutputId = "result"
