// Code generated by actrun. DO NOT EDIT.

package node_interfaces

import "github.com/actionforge/actrun-cli/core" // The Architecture Switch node allows to change the execution flow based on the platform of the system.

// ==> (o) Inputs

const Core_switch_platform_v1_Input_exec core.InputId = "exec"

// Outputs (o) ==> 

// Executes commands in a Linux environment.
const Core_switch_platform_v1_Output_exec_linux core.OutputId = "exec-linux"
// Executes commands in a MacOS environment.
const Core_switch_platform_v1_Output_exec_macos core.OutputId = "exec-macos"
// Executes commands in a Windows environment.
const Core_switch_platform_v1_Output_exec_win core.OutputId = "exec-win"
