// Code generated by actrun. DO NOT EDIT.

package node_interfaces

import "github.com/actionforge/actrun-cli/core" // Sort filepaths based on different criteria.

// ==> (o) Inputs

// A list of filepaths to sort.
const Core_filepath_sort_v1_Input_paths core.InputId = "paths"
// The criterion used for sorting.
const Core_filepath_sort_v1_Input_sort_by core.InputId = "sort_by"

// Outputs (o) ==> 

// The sorted list of filepaths.
const Core_filepath_sort_v1_Output_result core.OutputId = "result"
