// Code generated by actrun. DO NOT EDIT.

package node_interfaces

import "github.com/actionforge/actrun-cli/core" // Split a string into a slice using a delimiter with a limit.

// ==> (o) Inputs

const Core_string_split_v1_Input_delimiter core.InputId = "delimiter"
const Core_string_split_v1_Input_max_segments core.InputId = "max_segments"
const Core_string_split_v1_Input_string core.InputId = "string"

// Outputs (o) ==> 

const Core_string_split_v1_Output_segments core.OutputId = "segments"
