// Code generated by actrun. DO NOT EDIT.

package node_interfaces

import "github.com/actionforge/actrun-cli/core" // Walks through a directory and executes a body for each file

// ==> (o) Inputs

// Whether to include directories
const Core_dir_walk_v1_Input_dirs core.InputId = "dirs"
const Core_dir_walk_v1_Input_exec core.InputId = "exec"
// Whether to include files
const Core_dir_walk_v1_Input_files core.InputId = "files"
// The glob to match. It is applied on both, files and directories. See [Glob Pattern](./../../../reference/glob-pattern.md).
const Core_dir_walk_v1_Input_glob core.InputId = "glob"
// The directory to walk. use a single dot (`.`) for the current directory.
const Core_dir_walk_v1_Input_path core.InputId = "path"
// Whether to walk recursively
const Core_dir_walk_v1_Input_recursive core.InputId = "recursive"

// Outputs (o) ==> 

// Triggered if the input path is not a directory or if there is an error walking the directory. Also fails if an invalid glob pattern is set.
const Core_dir_walk_v1_Output_exec_err core.OutputId = "exec-err"
const Core_dir_walk_v1_Output_exec_success core.OutputId = "exec-success"
// The items that were walked with their absolute paths. The order is unspecified and determined by the underlying filesystem, but equal to the relative paths.
const Core_dir_walk_v1_Output_items_abs core.OutputId = "items_abs"
// The items that were walked with their relative paths. The order is unspecified and determined by the underlying filesystem, but equal to the absolute paths.
const Core_dir_walk_v1_Output_items_rel core.OutputId = "items_rel"
