// Code generated by actrun. DO NOT EDIT.

package node_interfaces

import "github.com/actionforge/actrun-cli/core" // Node to upload an object to a remote storage.

// ==> (o) Inputs

const Core_storage_upload_v1_Input_data core.InputId = "data"
const Core_storage_upload_v1_Input_exec core.InputId = "exec"
const Core_storage_upload_v1_Input_name core.InputId = "name"
const Core_storage_upload_v1_Input_provider core.InputId = "provider"

// Outputs (o) ==> 

const Core_storage_upload_v1_Output_exec_err core.OutputId = "exec-err"
const Core_storage_upload_v1_Output_exec_success core.OutputId = "exec-success"
const Core_storage_upload_v1_Output_provider core.OutputId = "provider"
