// Code generated by actrun. DO NOT EDIT.

package node_interfaces

import "github.com/actionforge/actrun-cli/core" // Returns specific locations like home directory or current graph path.

// ==> (o) Inputs

// Set of locations. Look at the addendum below for more information.
const Core_filepath_location_v1_Input_location core.InputId = "location"

// Outputs (o) ==> 

// The requested path.
const Core_filepath_location_v1_Output_result core.OutputId = "result"
