// Code generated by actrun. DO NOT EDIT.

package node_interfaces

import "github.com/actionforge/actrun-cli/core" // Generates text using a specified Large Language Model (LLM).

// ==> (o) Inputs

const Core_llm_prompt_v1_Input_Attachments core.InputId = "Attachments"
// The API key for the selected cloud provider.
const Core_llm_prompt_v1_Input_api_key core.InputId = "api_key"
const Core_llm_prompt_v1_Input_exec core.InputId = "exec"
// The name of the model to use. Check the documentation for supported models.
const Core_llm_prompt_v1_Input_model core.InputId = "model"
// The text prompt to send to the LLM.
const Core_llm_prompt_v1_Input_system_prompt core.InputId = "system_prompt"
// The text prompt to send to the LLM.
const Core_llm_prompt_v1_Input_user_prompt core.InputId = "user_prompt"

// Outputs (o) ==> 

// Executes if there is an error during text generation.
const Core_llm_prompt_v1_Output_exec_err core.OutputId = "exec-err"
// Executes if the text generation is successful.
const Core_llm_prompt_v1_Output_exec_success core.OutputId = "exec-success"
// The text generated by the LLM.
const Core_llm_prompt_v1_Output_response core.OutputId = "response"
