// Code generated by actrun. DO NOT EDIT.

package node_interfaces

import "github.com/actionforge/actrun-cli/core" // Iteratively executes contained nodes concurrently.

// ==> (o) Inputs

// Initiates the loop.
const Core_concurrent_for_loop_v1_Input_exec core.InputId = "exec"
// Starting point of the loop.
const Core_concurrent_for_loop_v1_Input_first_index core.InputId = "first_index"
// Ending point of the loop. Note, this value is inclusive. If the first index is 0 and the last index is 0, the node will iterate **once**. If you need to iterate zero times, the last index must be smaller than the first index.
const Core_concurrent_for_loop_v1_Input_last_index core.InputId = "last_index"
// Number of workers to use for concurrent execution.
const Core_concurrent_for_loop_v1_Input_worker_count core.InputId = "worker_count"

// Outputs (o) ==> 

// Executes on each iteration.
const Core_concurrent_for_loop_v1_Output_exec_body core.OutputId = "exec-body"
// Executes upon completion of the loop.
const Core_concurrent_for_loop_v1_Output_exec_completed core.OutputId = "exec-completed"
// Current iteration index.
const Core_concurrent_for_loop_v1_Output_index core.OutputId = "index"
