// Code generated by actrun. DO NOT EDIT.

package node_interfaces

import "github.com/actionforge/actrun-cli/core" // Provides statistics about local files or directories.

// ==> (o) Inputs

// Execution trigger for the node.
const Core_item_stats_v1_Input_exec core.InputId = "exec"
// Path to the file or directory to be examined.
const Core_item_stats_v1_Input_path core.InputId = "path"

// Outputs (o) ==> 

// Executed if the file or directory exists.
const Core_item_stats_v1_Output_exec_exists core.OutputId = "exec-exists"
// Executed if the file or directory does not exist.
const Core_item_stats_v1_Output_exec_noexists core.OutputId = "exec-noexists"
// Boolean indicating if the file or directory exists.
const Core_item_stats_v1_Output_exists core.OutputId = "exists"
// Boolean indicating if the path is a directory.
const Core_item_stats_v1_Output_isdir core.OutputId = "isdir"
// Boolean indicating if the path is a file.
const Core_item_stats_v1_Output_isfile core.OutputId = "isfile"
// The permissions of the file or directory.
const Core_item_stats_v1_Output_permissions core.OutputId = "permissions"
// The size of the file or directory in bytes.
const Core_item_stats_v1_Output_size core.OutputId = "size"
