// Code generated by actrun. DO NOT EDIT.

package node_interfaces

import "github.com/actionforge/actrun-cli/core" // Upload a file as a run artifact to the orchestrator.

// ==> (o) Inputs

// Optional alias name for the artifact. If set, this name is used instead of the filename.
const Core_artifact_upload_v1_Input_alias core.InputId = "alias"
// The data stream to upload as an artifact.
const Core_artifact_upload_v1_Input_data core.InputId = "data"
const Core_artifact_upload_v1_Input_exec core.InputId = "exec"
// The filename for the artifact.
const Core_artifact_upload_v1_Input_name core.InputId = "name"

// Outputs (o) ==>

const Core_artifact_upload_v1_Output_exec_err core.OutputId = "exec-err"
const Core_artifact_upload_v1_Output_exec_success core.OutputId = "exec-success"
