// Code generated by actrun. DO NOT EDIT.

package node_interfaces

import "github.com/actionforge/actrun-cli/core" // Converts a data structure into a string using a specified format.

// ==> (o) Inputs

// Executes the node.
const Core_serializer_v1_Input_exec core.InputId = "exec"
// The serialization format to use.
const Core_serializer_v1_Input_format core.InputId = "format"
// The data structure to serialize.
const Core_serializer_v1_Input_object core.InputId = "object"

// Outputs (o) ==> 

// Executes if serialization fails.
const Core_serializer_v1_Output_exec_err core.OutputId = "exec-err"
// Executes if serialization is successful.
const Core_serializer_v1_Output_exec_success core.OutputId = "exec-success"
// The serialized string.
const Core_serializer_v1_Output_output core.OutputId = "output"
