// Code generated by actrun. DO NOT EDIT.

package node_interfaces

import "github.com/actionforge/actrun-cli/core" // Download a run artifact from the orchestrator.

// ==> (o) Inputs

const Core_artifact_download_v1_Input_exec core.InputId = "exec"
// The filename of the artifact to download.
const Core_artifact_download_v1_Input_name core.InputId = "name"
// The run ID to download the artifact from. Defaults to the current run if empty.
const Core_artifact_download_v1_Input_run_id core.InputId = "run_id"

// Outputs (o) ==> 

// The downloaded artifact data stream.
const Core_artifact_download_v1_Output_data core.OutputId = "data"
const Core_artifact_download_v1_Output_exec_err core.OutputId = "exec-err"
const Core_artifact_download_v1_Output_exec_success core.OutputId = "exec-success"
