// Code generated by actrun. DO NOT EDIT.

package node_interfaces

import "github.com/actionforge/actrun-cli/core" // Concurrent Execution

// ==> (o) Inputs

const Core_concurrent_exec_v1_Input_exec core.InputId = "exec"

// Outputs (o) ==> 

const Core_concurrent_exec_v1_Output_exec core.OutputId = "exec"
// Executes upon completion of the loop.
const Core_concurrent_exec_v1_Output_exec_completed core.OutputId = "exec-completed"
