// Code generated by actrun. DO NOT EDIT.

package node_interfaces

import "github.com/actionforge/actrun-cli/core" // Compares two strings based on selected criteria.

// ==> (o) Inputs

// Type of comparison to perform
const Core_string_match_v1_Input_op core.InputId = "op"
// First string for comparison
const Core_string_match_v1_Input_str1 core.InputId = "str1"
// Second string for comparison
const Core_string_match_v1_Input_str2 core.InputId = "str2"

// Outputs (o) ==> 

// Output of the string comparison
const Core_string_match_v1_Output_result core.OutputId = "result"
