// Code generated by actrun. DO NOT EDIT.

package node_interfaces

import "github.com/actionforge/actrun-cli/core" // Iteratively executes contained nodes concurrently for each element in an array or map.

// ==> (o) Inputs

// Initiates the loop.
const Core_concurrent_for_each_loop_v1_Input_exec core.InputId = "exec"
const Core_concurrent_for_each_loop_v1_Input_input core.InputId = "input"
// Number of workers to use for concurrent execution.
const Core_concurrent_for_each_loop_v1_Input_worker_count core.InputId = "worker_count"

// Outputs (o) ==> 

// Executes on each iteration.
const Core_concurrent_for_each_loop_v1_Output_exec_body core.OutputId = "exec-body"
// Executes upon completion of the loop.
const Core_concurrent_for_each_loop_v1_Output_exec_completed core.OutputId = "exec-completed"
// A number index or key of a map.
const Core_concurrent_for_each_loop_v1_Output_key core.OutputId = "key"
// The value of the item
const Core_concurrent_for_each_loop_v1_Output_value core.OutputId = "value"
