// Code generated by actrun. DO NOT EDIT.

package node_interfaces

import "github.com/actionforge/actrun-cli/core" // Acts as an execution barrier, requiring a specified number of incoming executions before continuing.

// ==> (o) Inputs

const Core_wait_for_v1_Input_after core.InputId = "after"
const Core_wait_for_v1_Input_exec core.InputId = "exec"
const Core_wait_for_v1_Input_exec_reset core.InputId = "exec-reset"
const Core_wait_for_v1_Input_loop core.InputId = "loop"

// Outputs (o) ==> 

const Core_wait_for_v1_Output_exec core.OutputId = "exec"
