// Code generated by actrun. DO NOT EDIT.

package node_interfaces

import "github.com/actionforge/actrun-cli/core" // Node to delete an object on a remote storage.

// ==> (o) Inputs

const Core_storage_delete_v1_Input_exec core.InputId = "exec"
const Core_storage_delete_v1_Input_is_dir core.InputId = "is_dir"
const Core_storage_delete_v1_Input_name core.InputId = "name"
const Core_storage_delete_v1_Input_provider core.InputId = "provider"

// Outputs (o) ==> 

const Core_storage_delete_v1_Output_deleted core.OutputId = "deleted"
const Core_storage_delete_v1_Output_exec_err core.OutputId = "exec-err"
const Core_storage_delete_v1_Output_exec_success core.OutputId = "exec-success"
const Core_storage_delete_v1_Output_provider core.OutputId = "provider"
