// Code generated by actrun. DO NOT EDIT.

package node_interfaces

import "github.com/actionforge/actrun-cli/core" // Divides two or more numbers.

// ==> (o) Inputs

// A set of numbers with the first as the numerator and the rest as divisors.
const Core_math_divide_v1_Input_inputs core.InputId = "inputs"

// Outputs (o) ==> 

// The result of the division.
const Core_math_divide_v1_Output_result core.OutputId = "result"
