// Code generated by actrun. DO NOT EDIT.

package node_interfaces

import "github.com/actionforge/actrun-cli/core" // Array of numbers.

// ==> (o) Inputs

const Core_number_array_v1_Input_inputs core.InputId = "inputs"

// Outputs (o) ==> 

const Core_number_array_v1_Output_array core.OutputId = "array"
