// Code generated by actrun. DO NOT EDIT.

package node_interfaces

import "github.com/actionforge/actrun-cli/core" // Executes a series of outputs in sequential order.

// ==> (o) Inputs

// Triggers the execution sequence.
const Core_sequence_v1_Input_exec core.InputId = "exec"

// Outputs (o) ==> 

// An execution output in the sequence.
const Core_sequence_v1_Output_exec core.OutputId = "exec"
