// Code generated by actrun. DO NOT EDIT.

package node_interfaces

import "github.com/actionforge/actrun-cli/core" // Format a string using the provided format string.

// ==> (o) Inputs

// The format string with placeholders.
const Core_string_fmt_v1_Input_fmt core.InputId = "fmt"
// The input strings to replace the placeholders.
const Core_string_fmt_v1_Input_substitutes core.InputId = "substitutes"

// Outputs (o) ==> 

// Formatted String
const Core_string_fmt_v1_Output_result core.OutputId = "result"
