// Code generated by actrun. DO NOT EDIT.

package node_interfaces

import "github.com/actionforge/actrun-cli/core" // Freeze a value until a new value is provided.

// ==> (o) Inputs

const Core_freeze_v1_Input_exec core.InputId = "exec"
// Trigger this to replace the current value with the value provided in the `Replace` input.
const Core_freeze_v1_Input_exec_reset core.InputId = "exec-reset"
// The initial value to provide.
const Core_freeze_v1_Input_init core.InputId = "init"
// The value to replace the current value with.
const Core_freeze_v1_Input_replace core.InputId = "replace"

// Outputs (o) ==> 

const Core_freeze_v1_Output_exec core.OutputId = "exec"
// The value that is frozen.
const Core_freeze_v1_Output_value core.OutputId = "value"
