// Code generated by actrun. DO NOT EDIT.

package node_interfaces

import "github.com/actionforge/actrun-cli/core" // Perform operations on filepaths.

// ==> (o) Inputs

// Set of operations. Look at the addendum below for more information.
const Core_filepath_op_v1_Input_op core.InputId = "op"
const Core_filepath_op_v1_Input_path core.InputId = "path"

// Outputs (o) ==> 

const Core_filepath_op_v1_Output_result core.OutputId = "result"
