// Code generated by actrun. DO NOT EDIT.

package node_interfaces

import "github.com/actionforge/actrun-cli/core" // Set a value of the input object.

// ==> (o) Inputs

const Core_property_setter_v1_Input_exec core.InputId = "exec"
const Core_property_setter_v1_Input_object core.InputId = "object"
// The property path to set the value. See [Property Path](./../../../reference/property-paths.md) for more info.
const Core_property_setter_v1_Input_path core.InputId = "path"
const Core_property_setter_v1_Input_value core.InputId = "value"

// Outputs (o) ==> 

const Core_property_setter_v1_Output_exec_err core.OutputId = "exec-err"
const Core_property_setter_v1_Output_exec_success core.OutputId = "exec-success"
// The object with the property set. It is a deep copy of the input object.
const Core_property_setter_v1_Output_object core.OutputId = "object"
