// Code generated by actrun. DO NOT EDIT.

package node_interfaces

import "github.com/actionforge/actrun-cli/core" // Add two or more numbers.

// ==> (o) Inputs

// A set of numbers to add together.
const Core_math_add_v1_Input_inputs core.InputId = "inputs"

// Outputs (o) ==> 

// The result of the addition.
const Core_math_add_v1_Output_result core.OutputId = "result"
