// Code generated by actrun. DO NOT EDIT.

package node_interfaces

import "github.com/actionforge/actrun-cli/core" // Node to list objects on a remote storage.

// ==> (o) Inputs

// The directory prefix for the remote storage. Must **not** start with a slash. If left empty, it will list all objects at the root level. When a directory path is specified, only the first level of that directory will be listed. For subdirectories, use only forward slashes in the path.
const Core_storage_walk_v1_Input_dir core.InputId = "dir"
const Core_storage_walk_v1_Input_exec core.InputId = "exec"
// The glob to match. It is applied on both, files and directories.  The remote directory is walked in full, and the glob filter is then applied locally. See [Glob Pattern](./../../../reference/glob-pattern.md).
const Core_storage_walk_v1_Input_glob core.InputId = "glob"
const Core_storage_walk_v1_Input_provider core.InputId = "provider"

// Outputs (o) ==> 

// The list of directories at the specified location.
const Core_storage_walk_v1_Output_dirs core.OutputId = "dirs"
// Triggered if an error occured while listing objects. Also fails if an invalid glob pattern is set.
const Core_storage_walk_v1_Output_exec_err core.OutputId = "exec-err"
const Core_storage_walk_v1_Output_exec_success core.OutputId = "exec-success"
// The list of object items at the specified location.
const Core_storage_walk_v1_Output_objects core.OutputId = "objects"
const Core_storage_walk_v1_Output_provider core.OutputId = "provider"
