// Code generated by actrun. DO NOT EDIT.

package node_interfaces

import "github.com/actionforge/actrun-cli/core" // Conditional execution node for branching workflows.

// ==> (o) Inputs

// Boolean input that determines which branch to execute.
const Core_branch_v1_Input_condition core.InputId = "condition"
const Core_branch_v1_Input_exec core.InputId = "exec"

// Outputs (o) ==> 

// Executes the 'Otherwise' branch when the condition is false.
const Core_branch_v1_Output_exec_otherwise core.OutputId = "exec-otherwise"
// Executes the 'Then' branch when the condition is true.
const Core_branch_v1_Output_exec_then core.OutputId = "exec-then"
