// Code generated by actrun. DO NOT EDIT.

package node_interfaces

import "github.com/actionforge/actrun-cli/core" // Get an item from an array at a specified index.

// ==> (o) Inputs

// Input array
const Core_array_get_v1_Input_array core.InputId = "array"
// Perform bounds checking, otherwise returns an empty value
const Core_array_get_v1_Input_bound_check core.InputId = "bound_check"
// Index of the item to return (zero-based)
const Core_array_get_v1_Input_index core.InputId = "index"

// Outputs (o) ==> 

// Item at the specified index or nil if out of bounds
const Core_array_get_v1_Output_result core.OutputId = "result"
