// Code generated by actrun. DO NOT EDIT.

package node_interfaces

import "github.com/actionforge/actrun-cli/core" // Select an execution path based on the incoming execution index.

// ==> (o) Inputs

const Core_select_exec_v1_Input_exec core.InputId = "exec"

// Outputs (o) ==> 

const Core_select_exec_v1_Output_exec core.OutputId = "exec"
// The index of the incoming execution that triggered this node.
const Core_select_exec_v1_Output_index core.OutputId = "index"
