// Code generated by actrun. DO NOT EDIT.

package node_interfaces

import "github.com/actionforge/actrun-cli/core" // This S3 Provider node serves as a storage provider that can be plugged into other nodes offering cloud storage operations.


// ==> (o) Inputs

// The name of the S3 bucket you want to use.
const Core_storage_provider_s3_v1_Input_bucket core.InputId = "bucket"
// Your AWS credentials, consisting of an access key and a secret key. If left empty, the AWS SDK will use its default credential provider chain (environment variables, shared credentials file, IAM role, etc.).
const Core_storage_provider_s3_v1_Input_credentials core.InputId = "credentials"
// Only required for S3-compatible providers that are not AWS S3. E.g. needs to be set for Digital Ocean Spaces, Backblaze B2, etc. Here is a list of [S3-compatible providers](https://docs.aws.amazon.com/AmazonS3/latest/userguide/s3-compatible-storage-services.html).
const Core_storage_provider_s3_v1_Input_endpoint core.InputId = "endpoint"
// The region where the bucket is located.
const Core_storage_provider_s3_v1_Input_region core.InputId = "region"

// Outputs (o) ==> 

// The AWS S3 provider.
const Core_storage_provider_s3_v1_Output_provider core.OutputId = "provider"
