// Code generated by actrun. DO NOT EDIT.

package node_interfaces

import "github.com/actionforge/actrun-cli/core" // Bundles Perforce P4 connection details into a reusable credential object.

// ==> (o) Inputs

// The Perforce workspace/client name. Falls back to P4CLIENT env var if empty.
const Core_p4_credentials_v1_Input_client core.InputId = "client"
// The Perforce password or ticket. Falls back to P4PASSWD env var if empty.
const Core_p4_credentials_v1_Input_password core.InputId = "password"
// The Perforce server address. Falls back to P4PORT env var if empty.
const Core_p4_credentials_v1_Input_port core.InputId = "port"
// Path to the P4 trust file. Falls back to P4TRUST env var if empty.
const Core_p4_credentials_v1_Input_trust core.InputId = "trust"
// The Perforce username. Falls back to P4USER env var if empty.
const Core_p4_credentials_v1_Input_user core.InputId = "user"

// Outputs (o) ==> 

// A credential object containing the Perforce P4 connection details.
const Core_p4_credentials_v1_Output_credential core.OutputId = "credential"
