// Code generated by actrun. DO NOT EDIT.

package node_interfaces

import "github.com/actionforge/actrun-cli/core" // A node to set a secret value at runtime.

// ==> (o) Inputs

// Triggers the setting of the secret.
const Core_secret_set_v1_Input_exec core.InputId = "exec"
// The name of the secret to set.
const Core_secret_set_v1_Input_name core.InputId = "name"
// The value of the secret.
const Core_secret_set_v1_Input_value core.InputId = "value"

// Outputs (o) ==> 

// Triggered when the secret is successfully set.
const Core_secret_set_v1_Output_exec_success core.OutputId = "exec-success"
