// Code generated by actrun. DO NOT EDIT.

package node_interfaces

import "github.com/actionforge/actrun-cli/core" // Stages file changes in the working directory for the next commit (git add).

// ==> (o) Inputs

const Core_git_stage_v1_Input_exec core.InputId = "exec"
// A list of file paths or glob patterns to stage. Use '.' to stage all changes.
const Core_git_stage_v1_Input_paths core.InputId = "paths"
// The Git repository object from a clone or open node.
const Core_git_stage_v1_Input_repo core.InputId = "repo"

// Outputs (o) ==> 

// Executes if there is an error during staging.
const Core_git_stage_v1_Output_exec_err core.OutputId = "exec-err"
// Executes if the files are staged successfully.
const Core_git_stage_v1_Output_exec_success core.OutputId = "exec-success"
