// Code generated by actrun. DO NOT EDIT.

package node_interfaces

import "github.com/actionforge/actrun-cli/core" // Run executable

// ==> (o) Inputs

// Arguments to pass to the script.
const Core_run_exec_v1_Input_args core.InputId = "args"
// Environment variables to set before running the executable.
const Core_run_exec_v1_Input_env core.InputId = "env"
const Core_run_exec_v1_Input_exec core.InputId = "exec"
// Path to the executable.
const Core_run_exec_v1_Input_path core.InputId = "path"
// Option to capture the print to the stdout, to the output of the node or both.
const Core_run_exec_v1_Input_print core.InputId = "print"
// Stream to pass to the scripts stdin.
const Core_run_exec_v1_Input_stdin core.InputId = "stdin"

// Outputs (o) ==> 

const Core_run_exec_v1_Output_exec_err core.OutputId = "exec-err"
const Core_run_exec_v1_Output_exec_success core.OutputId = "exec-success"
const Core_run_exec_v1_Output_exit_code core.OutputId = "exit_code"
const Core_run_exec_v1_Output_output core.OutputId = "output"
