// Code generated by actrun. DO NOT EDIT.

package node_interfaces

import "github.com/actionforge/actrun-cli/core" // Subtract two or more numbers.

// ==> (o) Inputs

// A set of numbers with the first as the minuend and the rest as subtrahends.
const Core_math_subtract_v1_Input_inputs core.InputId = "inputs"

// Outputs (o) ==> 

// The result of the subtraction.
const Core_math_subtract_v1_Output_result core.OutputId = "result"
